{% set name = "landlab" %}
{% set version = 1.5.1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/landlab/landlab
  git_tag: v{{ version }}

requirements:
  build:
    - {{ compiler("c") }}
    - setuptools
    - python
    - cython
    - numpy 1.11.*

  run:
    - python
    - cython
    - numpy >=1.11,<1.14
    - scipy
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - six
    - pyyaml
    - statsmodels

test:
  requires:
    - landlab
    - numpy <1.14

build:
  number: 0
  string: {{ environ.get('BUILD_STR', '') }}
  script: python setup.py install --single-version-externally-managed --record record.txt
