{% set name = "landlab" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/landlab/landlab/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: 789f40c9aff30a5c350ef738f744506f197322d2123fa8e5711166bcda4f5635

requirements:
  build:
    - {{ compiler("c") }}
    - setuptools
    - python
    - pip
    - cython
    - numpy 1.11.*

  run:
    - python
    - cython
    - numpy >=1.11,<1.14
    - scipy
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - six
    - pyyaml
    - statsmodels

test:
  requires:
    - pytest
  imports:
    - landlab
#   commands:
#     - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
